apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    # Kubernetes containers logs
    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Tag               kube.*
        Parser            cri
        Refresh_Interval  5
        Skip_Long_Lines   On
        Mem_Buf_Limit     10MB
        DB                /var/log/flb_kube.db

    # Enrich with Kubernetes metadata
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            Off
        Labels              On
        Annotations         Off

    # Send to VictoriaLogs (victorialogs)
    [OUTPUT]
        Name    http
        Match   kube.*
        Host    victorialogs.logging.svc.cluster.local
        Port    9428
        URI     /insert/jsonline
        Format  json_lines
        # Optional: add custom headers
        # Header  X-TenantID    k8s

  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<flag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

