apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name         tail
        Path         /var/log/*.log
        Tag          kube.*
        Refresh_Interval 5
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [OUTPUT]
        Name  http
        Match kube.*
        Host  victorialogs.logging.svc.cluster.local
        Port  9428
        URI   /insert/jsonline
        Format json_lines

