apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://victoriametrics.monitoring.svc.cluster.local:8428
        isDefault: true
      - name: VictoriaLogs
        type: loki
        access: proxy
        url: http://victorialogs.logging.svc.cluster.local:9428
        basicAuth: false
        jsonData:
          maxLines: 2000

