apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victorialogs
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victorialogs
  template:
    metadata:
      labels:
        app: victorialogs
    spec:
      containers:
        - name: victorialogs
          image: victoriametrics/victoria-logs:v0.30.0
          args:
            - "--storageDataPath=/vlstorage"
            - "--retentionPeriod=7d"
            - "--httpListenAddr=:9428"
          ports:
            - containerPort: 9428
          volumeMounts:
            - mountPath: /vlstorage
              name: storage
      volumes:
        - name: storage
          emptyDir: {}   # Для теста, потом можно PVC
---
apiVersion: v1
kind: Service
metadata:
  name: victorialogs
  namespace: logging
spec:
  selector:
    app: victorialogs
  ports:
    - name: http
      port: 9428
      targetPort: 9428
  type: ClusterIP

