name: Apply Kubernetes Manifests

on:
  workflow_call:   # теперь его можно вызывать из других workflows

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Save kubeconfig
        run: |
          yc config set token $YC_TOKEN
          yc config set cloud-id $YC_CLOUD_ID
          yc config set folder-id $YC_FOLDER_ID
          yc managed-kubernetes cluster get-credentials otus-k8s-cluster \
            --external --force --kubeconfig kubeconfig
        env:
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
          YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
          YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.31.0'

      - name: Apply manifests
        env:
          KUBECONFIG: ./kubeconfig
        run: |
          # Apply all manifests except user dashboards kustomize dir
          find k8s -type f \( -name '*.yaml' -o -name '*.yml' -o -name '*.json' \) \
            ! -path 'k8s/monitoring/grafana-dashboards-user/*' -print0 | \
            xargs -0 -n1 kubectl apply -f
          # Apply user Grafana dashboards (kustomize)
          kubectl apply -k k8s/monitoring/grafana-dashboards-user
          
      - name: Check pods
        env:
          KUBECONFIG: ./kubeconfig
        run: kubectl get pods -A -o wide

